# ==========================================
# РІВЕНЬ 1
# ==========================================
[[levels]]
id = 1
lab_text = """
Перетягніть з початку(жовтий)
    до кінця(синій) поїзд
Завдяки рейкам(забавне слово)"""

[[levels.pazls]]
type = ""
count = 3